{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "bom",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.example",
          "module": "library-a",
          "version": {
            "strictly": "[1.0-SNAPSHOT, 1.1-SNAPSHOT]",
            "requires": "[1.0-SNAPSHOT, 1.1-SNAPSHOT]",
            "prefers": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.example",
          "module": "library-b",
          "version": {
            "strictly": "[1.5-SNAPSHOT, 1.6)",
            "requires": "[1.5-SNAPSHOT, 1.6)",
            "prefers": "1.5-SNAPSHOT"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.example",
          "module": "library-a",
          "version": {
            "strictly": "[1.0-SNAPSHOT, 1.1-SNAPSHOT]",
            "requires": "[1.0-SNAPSHOT, 1.1-SNAPSHOT]",
            "prefers": "1.1-SNAPSHOT"
          }
        },
        {
          "group": "com.example",
          "module": "library-b",
          "version": {
            "strictly": "[1.5-SNAPSHOT, 1.6)",
            "requires": "[1.5-SNAPSHOT, 1.6)",
            "prefers": "1.5-SNAPSHOT"
          }
        }
      ]
    }
  ]
}
