package gcpauth

import (
	"context"
	"fmt"
	"os"
	"strings"
	"sync"

	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"

	"github.com/aquasecurity/trivy/pkg/log"
)

var (
	// Global token cache to avoid repeatedly calling GCP APIs
	tokenCache     *oauth2.Token
	tokenCacheMu   sync.RWMutex
	gcpCredentials *google.Credentials
	logger         = log.WithPrefix("gcp-auth")
)

const (
	cloudPlatformScope = "https://www.googleapis.com/auth/cloud-platform"
)

// IsGCPArtifactRegistry checks if URL is GCP Artifact Registry
func IsGCPArtifactRegistry(url string) bool {
	isGCP := strings.Contains(url, ".pkg.dev")
	if isGCP {
		logger.Debug("Detected GCP Artifact Registry URL", log.String("url", url))
	}
	return isGCP
}

// IsGCSBucket checks if URL is a GCS bucket with gcs:// protocol
func IsGCSBucket(url string) bool {
	isGCS := strings.HasPrefix(url, "gcs://")
	if isGCS {
		logger.Debug("Detected GCS bucket URL", log.String("url", url))
	}
	return isGCS
}

// IsGCPRepository checks if URL is any GCP-hosted repository (Artifact Registry or GCS bucket)
func IsGCPRepository(url string) bool {
	return IsGCPArtifactRegistry(url) || IsGCSBucket(url)
}

// ConvertGCSToHTTPS converts gcs:// URLs to HTTPS format for HTTP requests
// Example: gcs://repo.revolut.com/snapshots -> https://storage.googleapis.com/repo.revolut.com/snapshots
func ConvertGCSToHTTPS(gcsURL string) (string, error) {
	if !strings.HasPrefix(gcsURL, "gcs://") {
		return gcsURL, nil // Not a GCS URL, return as-is
	}

	// Remove gcs:// prefix
	path := strings.TrimPrefix(gcsURL, "gcs://")
	if path == "" {
		return "", fmt.Errorf("invalid GCS URL: %s", gcsURL)
	}

	// Convert to HTTPS URL
	httpsURL := fmt.Sprintf("https://storage.googleapis.com/%s", path)

	logger.Debug("Converted GCS URL to HTTPS",
		log.String("original", gcsURL),
		log.String("converted", httpsURL))

	return httpsURL, nil
}

// IsGCPAuthEnabled checks if GOOGLE_APPLICATION_CREDENTIALS env var is set
func IsGCPAuthEnabled() bool {
	credPath := os.Getenv("GOOGLE_APPLICATION_CREDENTIALS")
	if credPath != "" {
		logger.Debug("GOOGLE_APPLICATION_CREDENTIALS is set", log.String("path", credPath))
		return true
	}
	logger.Debug("GOOGLE_APPLICATION_CREDENTIALS is not set, GCP auth disabled")
	return false
}

// GetGCPAccessToken generates or returns cached OAuth2 token
// Only works if GOOGLE_APPLICATION_CREDENTIALS is set
func GetGCPAccessToken(ctx context.Context) (string, error) {
	// Check if GCP auth is enabled
	credPath := os.Getenv("GOOGLE_APPLICATION_CREDENTIALS")
	if credPath == "" {
		return "", fmt.Errorf("GOOGLE_APPLICATION_CREDENTIALS not set")
	}

	logger.Debug("Attempting to get GCP access token")

	// Check cache first
	tokenCacheMu.RLock()
	if tokenCache != nil && tokenCache.Valid() {
		token := tokenCache.AccessToken
		tokenCacheMu.RUnlock()
		logger.Debug("Using cached GCP access token")
		return token, nil
	}
	tokenCacheMu.RUnlock()

	logger.Debug("Token not cached or expired, generating new token")

	tokenCacheMu.Lock()
	defer tokenCacheMu.Unlock()

	// Double-check after acquiring write lock
	if tokenCache != nil && tokenCache.Valid() {
		logger.Debug("Token was generated by another goroutine, using cached token")
		return tokenCache.AccessToken, nil
	}

	// Initialize credentials if not already done
	if gcpCredentials == nil {
		logger.Debug("Reading GCP credentials file", log.String("path", credPath))

		data, err := os.ReadFile(credPath)
		if err != nil {
			return "", fmt.Errorf("failed to read GCP credentials file %s: %w", credPath, err)
		}

		logger.Debug("Parsing GCP credentials JSON")
		creds, err := google.CredentialsFromJSON(ctx, data, cloudPlatformScope)
		if err != nil {
			return "", fmt.Errorf("failed to parse GCP credentials: %w", err)
		}
		gcpCredentials = creds
		logger.Info("GCP credentials loaded successfully")
	}

	// Get new token
	logger.Debug("Requesting new access token from GCP")
	token, err := gcpCredentials.TokenSource.Token()
	if err != nil {
		return "", fmt.Errorf("failed to get GCP access token: %w", err)
	}

	tokenCache = token
	logger.Info("Successfully generated GCP access token")

	return token.AccessToken, nil
}
