name: Release Aikido
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/build-aikido.yaml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Deploy to GitHub Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2
        with:
          files: |
            dist/trivy-${{ github.ref_name }}-linux-amd64
