name: Release Aikido
on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Trivy
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2.1.0
          args: release --snapshot --skip-publish --clean -f=goreleaser.yml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trivy-binaries
          path: dist/*
