name: Release test
on: workflow_dispatch

env:
  GO_VERSION: '1.22'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false # Disable cache to avoid free space issues during `Post Setup Go` step.


      # Create tmp dir for GoReleaser
      - name: "create tmp dir"
        run: |
          mkdir tmp

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: v2.1.0
          args: release -f=${{ inputs.goreleaser_config}} ${{ inputs.goreleaser_options}}
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
          TMPDIR: "tmp"

